name: discovering-disease-outbreaks
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - basemap
  - black
  - matplotlib
  - seaborn
  - Unidecode
  - pip
  - Pillow
  - jupyter
  - jupyter_contrib_nbextensions
  - nbconvert
  - pip:
      - geonamescache
